### ISSUE TITLE
Use custom ssh key (ssh -i)

### ISSUE THREAD

**Issue by candidtim** [aeroxis/sultan#31]
In Sultan context for remote host, is there a way to connect to remote host with a custom SSH key? Like one would otherwise do with `ssh -i mykeyfile.pem user@host`.

Thank you!

**Comment by peetasan** [comment]
You could add this to your `~/.ssh/config` file:

```
Host myhost
  IdentityFile ~/.ssh/mykeyfile.pem
```

`user` and `hostname` should be passed as arguments to `Sultan.load()`

**Comment by davydany** [comment]
I'd recommend the method recommended by @peetasan because I think that is the right approach to set identity files. Your SSH Key is considered private, and you should not be putting the location to it or contents of it in your bash file. 

That being said, I do see the use cases when you need to specify your identity key in your script. I'll add that as a feature in the next release.

**Comment by davydany** [comment]
I implemented this in `v0.6`, and released it today. Here is the documentation for it: http://sultan.readthedocs.io/en/latest/sultan-ssh-examples.html#example-4-passing-additional-options-identity-file

I'm closing the ticket, but feel free to reopen it if it is still an issue.
